######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 10 12:39:04 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += precompile_header

# Input
HEADERS += foo.h
SOURCES += foo.cpp main.cpp test.c

PRECOMPILED_HEADER = stable.h
PRECOMPILED_DIR = .precompiled
