######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 10 12:39:04 2012
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += precompile_header

# Input
HEADERS += foo.h
#SOURCES += foo.cpp main.cpp test.c
SOURCES += foo.cpp 

PRECOMPILED_HEADER = stable.h
PRECOMPILED_DIR = .precompiled
