/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DaemonInterface -p daemoninterface.h:daemoninterface.cpp rtags.Daemon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DAEMONINTERFACE_H_1311146866
#define DAEMONINTERFACE_H_1311146866

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface rtags.Daemon
 */
class DaemonInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "rtags.Daemon"; }

public:
    DaemonInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~DaemonInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> runCommand(const QStringList &args)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(args);
        return asyncCallWithArgumentList(QLatin1String("runCommand"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace rtags {
  typedef ::DaemonInterface Daemon;
}
#endif
