/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DaemonAdaptor -a DaemonAdaptor.h:DaemonAdaptor.cpp rtags.Daemon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "DaemonAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DaemonAdaptor
 */

DaemonAdaptor::DaemonAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DaemonAdaptor::~DaemonAdaptor()
{
    // destructor
}

ArgumentMap DaemonAdaptor::runCommand(const ArgumentMap &args)
{
    // handle method call rtags.Daemon.runCommand
    ArgumentMap out0;
    QMetaObject::invokeMethod(parent(), "runCommand", Q_RETURN_ARG(ArgumentMap, out0), Q_ARG(ArgumentMap, args));
    return out0;
}

