/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DaemonAdaptor -a DaemonAdaptor.h:DaemonAdaptor.cpp rtags.Daemon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DAEMONADAPTOR_H_1311705433
#define DAEMONADAPTOR_H_1311705433

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface rtags.Daemon
 */
class DaemonAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "rtags.Daemon")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"rtags.Daemon\">\n"
"    <method name=\"runCommand\">\n"
"      <arg direction=\"out\" type=\"a{sv}\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"args\"/>\n"
"      <annotation value=\"QHash<QByteArray, QVariant>\" name=\"com.trolltech.QtDBus.QtTypeName.Out0\"/>\n"
"      <annotation value=\"QHash<QByteArray, QVariant>\" name=\"com.trolltech.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    DaemonAdaptor(QObject *parent);
    virtual ~DaemonAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QHash<QByteArray, QVariant> runCommand(const QHash<QByteArray, QVariant> &args);
Q_SIGNALS: // SIGNALS
};

#endif
