######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 19 22:01:12 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
