######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 10 17:09:43 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
