# File: sbroot_test/main/Makefile
# Abstract:
#   Used to build all *.cpp files in current directory.


MODULE_TYPE = Executable
MODULE_NAME = sbroot_test
MODULE_LIBS = sub1
include ../make/module.mk

