######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 9 13:09:44 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += simple.h header.h
SOURCES += main.cpp simple.cpp
