######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 26 10:12:24 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG -= qt

# Input
SOURCES += main.cpp
