######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 18 18:08:50 2012
######################################################################

TEMPLATE = app
TARGET = foobar
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp foo1.cpp foo2.cpp foo3.cpp foo4.cpp
PRECOMPILED_HEADER = pch.h
CONFIG += precompile_header
PRECOMPILED_DIR = .pch
