######################################################################
# Automatically generated by qmake (2.01a) Thu May 10 22:17:00 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Foo.h
SOURCES += main.cpp Foo.cpp 
