######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 15 21:37:42 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG -= qt

# Input
HEADERS += test.h
SOURCES += main.cpp test.cpp
