######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 1 11:16:08 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Class.h Struct.h
SOURCES += Class.cpp main.cpp
QT = 
