######################################################################
# Automatically generated by qmake (2.01a) Wed May 9 17:08:13 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += foo.h header.h
SOURCES += foo.cpp main.cpp
