######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 10 19:53:50 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .

# Input
SOURCES += main.cpp
CONFIG -= app_bundle
include($$PWD/../shared/clang.pri)

