######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 10 19:53:50 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . /usr/local/include/
LIBS += -lclang -L/usr/local/lib

# Input
SOURCES += main.cpp
