######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 21 01:58:56 2011
######################################################################

TEMPLATE = app
TARGET = rc
DESTDIR = ..
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += rclient.c 
CONFIG += debug
CONFIG -= app_bundle
QT = 
unix {
    OBJECTS_DIR = .obj
}
 
QMAKE_LINK = $$QMAKE_LINK_C
include(../shared/shared.pri)
