######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 9 09:50:58 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += c.h
SOURCES += c.cpp main.cpp
