######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 12 13:55:14 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
