######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 12 23:22:20 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG -= qt

# Input
HEADERS += test.h
SOURCES += main.cpp test.cpp
