######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 26 22:07:36 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG -= qt

# Input
HEADERS += test1.h
SOURCES += main.cpp test1.cpp
