######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 15 22:45:11 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG -= qt

# Input
HEADERS += test1.h
SOURCES += main.cpp test1.cpp
