######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 13 18:55:37 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
