######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 19 16:14:00 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
PRECOMPILED_HEADER = pch.h
CONFIG += precompile_header
PRECOMPILED_DIR = .pch
 
