######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 25 14:20:56 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT =
