if(EXISTS ${PROJECT_SOURCE_DIR}/3rdparty/clang_install/include/clang-c/Index.h)
  set(clang_ROOT ${PROJECT_SOURCE_DIR}/3rdparty/clang_install/)
  set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
  include_directories(${clang_ROOT}/include)
  if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(clang_LIBS ${clang_ROOT}/lib/libclang.dylib)
  else()
    set(clang_LIBS ${clang_ROOT}/lib/libclang.so)
  endif()
  set(GRTAGS_ENABLED 1)
else()
  find_package(LibClang REQUIRED)
  include_directories(${LibClang_INCLUDE_DIRS})
  set(clang_LIBS ${LibClang_LIBRARIES})
endif()

