(eval-when-compile
  (defun company-grab-symbol (&rest args))
  (defun company-begin-backend (&rest args))
  (defun company-in-string-or-comment (&rest args))
  (defun company-template-c-like-templatify (&rest args))
  (defun completing-read-default (&rest args))
  (defun popup-tip (&rest args))
  (defun yas-expand-snippet (&rest args))
  (defun ac-prefix-symbol (&rest args))
  (defun ac-start (&rest args))
  (defun ac-define-source (&rest args))
  (defun cl-mapcan (&rest args))
  (defun helm (&rest args))
  (defvar company-async-wait nil)
  (defvar rtags nil)
  (defvar ac-last-completion nil)

  (provide 'company)
  (provide 'company-template)
  (provide 'auto-complete)
  (provide 'helm))
