DECLARE_INCLUDE_TYPE(Type_DirAfter, "-idirafter", " ")
DECLARE_INCLUDE_TYPE(Type_File, "-include", " ")
DECLARE_INCLUDE_TYPE(Type_Framework, "-F", "")
DECLARE_INCLUDE_TYPE(Type_Include, "-I", "")
DECLARE_INCLUDE_TYPE(Type_Macros, "-imacros", " ")
DECLARE_INCLUDE_TYPE(Type_MultiLib, "-imultilib", " ")
DECLARE_INCLUDE_TYPE(Type_PCH, "-include-pch", " ")
DECLARE_INCLUDE_TYPE(Type_Prefix, "-iprefix", " ")
DECLARE_INCLUDE_TYPE(Type_Quote, "-iquote", " ")
DECLARE_INCLUDE_TYPE(Type_Sysroot, "-isysroot", " ")
DECLARE_INCLUDE_TYPE(Type_System, "-isystem", " ")
DECLARE_INCLUDE_TYPE(Type_SystemFramework, "-iframework", " ")
DECLARE_INCLUDE_TYPE(Type_WithPrefix, "-iwithprefix", " ")
DECLARE_INCLUDE_TYPE(Type_WithPrefixBefore, "-iwithprefixbefore", " ")
