######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 17 11:51:00 2012
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += plugin

# Input
SOURCES += makelib.cpp
