set(FORCE_BASH_COMPLETION_INSTALLATION FALSE CACHE BOOL "Always install bash completion files (default installation path /usr/share/bash-completion/completions)")

if(FORCE_BASH_COMPLETION_INSTALLATION AND "${BASH_COMPLETION_COMPLETIONSDIR}" STREQUAL "")
    set(BASH_COMPLETION_COMPLETIONSDIR "/usr/share/bash-completion/completions")
endif()

find_package(PkgConfig QUIET)
if(PKG_CONFIG_FOUND OR FORCE_BASH_COMPLETION_INSTALLATION)
    if(PKG_CONFIG_FOUND AND NOT FORCE_BASH_COMPLETION_INSTALLATION)
        execute_process(COMMAND ${PKG_CONFIG_EXECUTABLE} --variable=completionsdir bash-completion
            RESULT_VARIABLE BASH_COMPLETION_UNAVAILABLE
            OUTPUT_VARIABLE BASH_COMPLETION_COMPLETIONSDIR
            ERROR_QUIET
            OUTPUT_STRIP_TRAILING_WHITESPACE)
    endif()
    if(NOT BASH_COMPLETION_UNAVAILABLE OR FORCE_BASH_COMPLETION_INSTALLATION)
	set(BASH_COMPLETION_COMPLETIONSDIR ${BASH_COMPLETION_COMPLETIONSDIR} CACHE PATH "Bash completion installation directory")
        if(${CMAKE_INSTALL_PREFIX} MATCHES "^/usr")
            string(REGEX REPLACE "^/usr" "" BASH_COMPLETION_COMPLETIONSDIR ${BASH_COMPLETION_COMPLETIONSDIR})
        endif()
	set(BASH_COMPLETION_COMPLETIONSDIR "${CMAKE_INSTALL_PREFIX}${BASH_COMPLETION_COMPLETIONSDIR}")
        mark_as_advanced(BASH_COMPLETION_COMPLETIONSDIR)
        set(BASH_COMPLETION_FOUND TRUE)
    endif()
endif()
