######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 27 17:49:55 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
